name: CI
on: push

jobs:
  build:
    if: contains(github.event.head_commit.message, 'publish')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: |
          yarn
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-shanghai.aliyuncs.com
          access-key-id: ${{ secrets.ACCESSKEYID }}
          access-key-secret: ${{ secrets.ACCESSKEYSECRET }}
      - run: ossutil cp -rf ./android/app/build/outputs/apk/release/jieapp.apk oss://luhaojie/apks/

      - name: Send success message
        if: success()
        run: |
          curl -G "https://wss.laihaojie.com/api/tools/releaseSuccess" --data-urlencode "id=阿杰的APP"
          curl -X GET "https://api.laihaojie.com/api/public/updateAndroidVersion"

      - name: Send failed message
        if: failure()
        run: curl -G "https://wss.laihaojie.com/api/tools/releaseFailed" --data-urlencode "id=阿杰的APP"
